//SPDX-License-Identifier: Apache-2.0 AND CC-BY-SA-3.0
#pragma once

// The following is adapted from https://en.wikipedia.org/wiki/ANSI_escape_code
// Permalink: https://en.wikipedia.org/w/index.php?oldid=1291641590
// As per the terms of use, a link is acceptable attribution
// The license text may be found here: https://creativecommons.org/licenses/by-sa/4.0/deed.en
// Licensed under CC-BY-SA. No warranties are provided. See the licence for details.

// Also partially derived from https://gist.github.com/fnky/458719343aabd01cfb17a3a4f7296797
// (no licence provided, but considering the volume of forks and the
// intention to provide a guide for an identifiable standard, it's fine)

// All codes have no separators - e.g. all arguments need
// semicolons in between.

/* == begin CC material == */
#define C0_BELL					"\x07" // \a
#define C0_BACKSPACE			"\x08"
#define C0_TAB					"\x09" // \t
#define C0_LINE_FEED			"\x0A" // \n
#define C0_FORM_FEED			"\x0D"
#define C0_ESCAPE				"\x1B" // (not for use in other macros)

#define FE_CUR_UP_SCROLL		"\x1BM"
#define FE_SINGLE_SHIFT_2		"\x1BN"
#define FE_SINGLE_SHIFT_3		"\x1BO"
#define FE_DEVICE_CONTROL		"\x1BP"
#define FE_CSI					"\x1B["
#define FE_STRING_TERM			"\x1B\\"
#define FE_OS_COMMAND			"\x1B]"
#define FE_STRING_START			"\x1B]"
#define FE_PRIV_MSG				"\x1B^"
#define FE_APP_COMMAND			"\x1B_"

#define FP_DEC_SAVE				"\x1B7"
#define FP_DEC_RESTORE			"\x1B8"

#define CSI_CURSOR_UP			"A"
#define CSI_CURSOR_DOWN			"B"
#define CSI_CURSOR_FORWARD		"C"
#define CSI_CURSOR_BACK			"D"
#define CSI_CURSOR_NEXTLN		"E"
#define CSI_CURSOR_PREVLN		"F"
#define CSI_CURSOR_HORIZABS		"G"
#define CSI_CURSOR_ABSOLUTE		"H"
#define CSI_ERASE				"J"
#define CSI_ERSLN				"K"
#define CSI_SCROLL_UP			"S"
#define CSI_SCROLL_DOWN			"T"
#define CSI_HVPOS				"f"
#define CSI_AUXON				"5i"
#define CSI_AUXOFF				"4i"
#define CSI_GET_CURPOS			"6n"
#define CSI_SCO_SAVE_PRIV		"s"
#define CSI_SCO_REST_PRIV		"u"
#define CSI_GRAPHICS_SGR		"m"

#define CSI_ERASE_CUREND		"0"
#define CSI_ERASE_CURSTART	"1"
#define CSI_ERASE_ALL			"2"
#define CSI_ERASE_SCRBK		"3"
#define CSI_ERSLN_CUREND		"0"
#define CSI_ERSLN_CURSTART	"1"
#define CSI_ERSLN_ALL			"2"

#define SGR_RESET				"0"
#define SGR_BOLD				"1"
#define SGR_FAINT				"2"
#define SGR_ITALIC				"3"
#define SGR_UNDERLINE			"4"
#define SGR_BLINKSLOW			"5"
#define SGR_BLINKFAST			"6"
#define SGR_INVERT				"7"
#define SGR_HIDE				"8"
#define SGR_STRIKETHROUGH		"9"
#define SGR_FONT_PRIMARY		"10"
#define SGR_FONT_1				"11"
#define SGR_FONT_2				"12"
#define SGR_FONT_3				"13"
#define SGR_FONT_4				"14"
#define SGR_FONT_5				"15"
#define SGR_FONT_6				"16"
#define SGR_FONT_7				"17"
#define SGR_FONT_8				"18"
#define SGR_FONT_9				"19"
#define SGR_FRAKTUR				"20"
#define SGR_2UNDERLINE_NOBOLD	"21"
#define SGR_NOT_BOLD_FAINT		"22"
#define SGR_NOT_ITALIC_BLKLTR	"23"
#define SGR_NOT_UNDERLINED		"24"
#define SGR_NOT_BLINKING		"25"
#define SGR_PROPORTIONAL		"26"
#define SGR_NOT_REVERSED		"27"
#define SGR_NOT_CONCEALED		"28"
#define SGR_NOT_STRUCK			"29"
#define SGR_BG_BLACK			"30"
#define SGR_BG_RED				"31"
#define SGR_BG_GREEN			"32"
#define SGR_BG_YELLOW			"33"
#define SGR_BG_BLUE				"34"
#define SGR_BG_MAGENTA			"35"
#define SGR_BG_CYAN				"36"
#define SGR_BG_WHITE			"37"
#define SGR_BG_HICOLOUR			"38"
#define SGR_BG_DEFAULT			"39"
#define SGR_FG_BLACK			"40"
#define SGR_FG_RED				"41"
#define SGR_FG_GREEN			"42"
#define SGR_FG_YELLOW			"43"
#define SGR_FG_BLUE				"44"
#define SGR_FG_MAGENTA			"45"
#define SGR_FG_CYAN				"46"
#define SGR_FG_WHITE			"47"
#define SGR_FG_HICOLOUR			"48"
#define SGR_FG_DEFAULT			"49"
#define SGR_NOT_PROPORTIONAL	"50"
#define SGR_FRAMED				"51"
#define SGR_CIRCLED				"52"
#define SGR_OVERLINED			"53"
#define SGR_NOT_FRAMED_CIRCLED	"54"
#define SGR_NOT_OVERLINED		"55"
#define SGR_UNDRLN_CLR_HI_PRIV	"58"
#define SGR_UNDRLN_CLR_DF_PRIV	"59"
#define SGR_IDEO_UNDRLN_RSL		"60"
#define SGR_IDEO_DBL_UNDRLN_RSL	"61"
#define SGR_IDEO_OVRLN_LSL		"62"
#define SGR_IDEO_DBL_OVRLN_LSL	"63"
#define SGR_IDEO_STRESS			"64"
#define SGR_IDEO_NONE			"64"
#define SGR_SUPERSCRIPT_PRIV	"73"
#define SGR_SUBSCRIPT_PRIV		"74"
#define SGR_NOSCRIPT_PRIV		"75"
#define SGR_BG_BRIGHT_BLACK		"30"
#define SGR_BG_BRIGHT_RED		"31"
#define SGR_BG_BRIGHT_GREEN		"32"
#define SGR_BG_BRIGHT_YELLOW	"33"
#define SGR_BG_BRIGHT_BLUE		"34"
#define SGR_BG_BRIGHT_MAGENTA	"35"
#define SGR_BG_BRIGHT_CYAN		"36"
#define SGR_BG_BRIGHT_WHITE		"37"
#define SGR_FG_BRIGHT_BLACK		"40"
#define SGR_FG_BRIGHT_RED		"41"
#define SGR_FG_BRIGHT_GREEN		"42"
#define SGR_FG_BRIGHT_YELLOW	"43"
#define SGR_FG_BRIGHT_BLUE		"44"
#define SGR_FG_BRIGHT_MAGENTA	"45"
#define SGR_FG_BRIGHT_CYAN		"46"
#define SGR_FG_BRIGHT_WHITE		"47"

#define SGR_COLOUR_256			"5"
#define SGR_COLOUR_TRUE			"2"

#define SGR_TERM				"m"
/* == end CC material == */
